Create Your First Tensor 🎉

In [2]:
import torch

In [ ]:
x = torch.tensor([1, 2, 3])

print(x)

tensor([1, 2, 3])


2D Tensor


In [4]:
x = torch.tensor([
    [1, 2],
    [3, 4]
])

print(x)
print(f"x shape: {x.shape}")

tensor([[1, 2],
        [3, 4]])
x shape: torch.Size([2, 2])


In [ ]:
# 3D Tensor
x = torch.tensor([
    [
        [1,2],
        [3,4]
    ],
    [
        [5.5,6],
        [7,8]
    ]
])

print(x)
print(x.shape) # checks the shape of the tensor
print(x.dtype) # checks the data type of the tensor
print(x.device) # checks if the tensor is on CPU or GPU
print(torch.cuda.is_available()) # checks if GPU is available

tensor([[[1.0000, 2.0000],
         [3.0000, 4.0000]],

        [[5.5000, 6.0000],
         [7.0000, 8.0000]]])
torch.Size([2, 2, 2])
torch.float32
cpu
False
