Create Your First Tensor 🎉

In [ ]:
import torch

In [ ]:
x = torch.tensor([1, 2, 3])

print(x)

tensor([1, 2, 3])


2D Tensor


In [6]:
x = torch.tensor([
    [1, 2],
    [3, 4]
])

print(x)

tensor([[1, 2],
        [3, 4]])


In [7]:
# 3D Tensor
x = torch.tensor([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

print(x)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
