Create Your First Tensor 🎉

In [3]:
import torch

In [ ]:
x = torch.tensor([1, 2, 3])

print(x)

tensor([1, 2, 3])


2D Tensor


In [4]:
x = torch.tensor([
    [1, 2],
    [3, 4]
])

print(x)
print(f"x shape: {x.shape}")

tensor([[1, 2],
        [3, 4]])
x shape: torch.Size([2, 2])


In [ ]:
# 3D Tensor
x = torch.tensor([
    [
        [1,2],
        [3,4]
    ],
    [
        [5.5,6],
        [7,8]
    ]
])

print(x)
print(x.shape) # checks the shape of the tensor
print(x.dtype) # checks the data type of the tensor
print(x.device) # checks if the tensor is on CPU or GPU
print(torch.cuda.is_available()) # checks if GPU is available

tensor([[[1.0000, 2.0000],
         [3.0000, 4.0000]],

        [[5.5000, 6.0000],
         [7.0000, 8.0000]]])
torch.Size([2, 2, 2])
torch.float32
cpu
False


In [15]:

# Basic Math ⭐⭐⭐⭐⭐

a = torch.tensor([1, 2, 3])

b = torch.tensor([4, 5, 6])

c = torch.tensor([4, 8, 6])

print(a * b + c) # element-wise multiplication and addition

tensor([ 8, 18, 24])


In [18]:
# Indexing ⭐⭐⭐⭐⭐

x = torch.tensor([10, 20, 30])

print(x[2])

tensor(30)


In [ ]:
# ReShape -> 🪸 change tensor to 2d to 3d or any other

x = torch.tensor([1, 2, 3, 4])

print(x.reshape(2, 2)) # Convert to 2D tensor with shape (2, 2)

tensor([[1, 2],
        [3, 4]])


##### Which numbers inside the model should change, and by how much? -> "Auto Grad" 🧠

Gradient = Tell which direct weights should change, and by how much so it can reduce the loss.

requires_grad =  tells PyTorch to track all operations on the tensor(number). 

backward() =  computes the gradient of the loss with respect to the parameters (or anything requiring gradients) using backpropagation.


    

<!-- #y -->

In [ ]:
# backward() -> backpropagation is the process of calculating the gradient of the loss function with respect to the model's parameters. It is a key step in training neural networks, allowing the model to learn from its errors and improve its performance.

weight = torch.tensor(2.0, requires_grad=True)


y = weight * 5
y.backward()


None


C:\Users\chand\AppData\Local\Temp\ipykernel_5652\2593021506.py:8: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:499.)
  print(y.grad)


In [ ]:
import torch

x = torch.tensor(2.0, requires_grad=True)

y = x * 5

y.backward()

print(x.grad) # It tell which direct weights should change, and by how much so it can reduce the loss. 

tensor(5.)
